project:
  type: website

website:
  title: "By The Numbers"
  navbar:
    title: "By The Numbers"
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
